@echo off
:: ============================================================
:: install.bat  —  wsl-mcp-shutdown Windows installer
:: Requirements: Python 3.9+ must already be on PATH
:: Run from the repo root in a regular cmd.exe window
:: (no Administrator rights needed)
:: ============================================================

setlocal EnableDelayedExpansion

set "REPO_DIR=%~dp0"
set "STARTUP_DIR=%APPDATA%\Microsoft\Windows\Start Menu\Programs\Startup"
set "VENV_DIR=%REPO_DIR%.venv"
set "LAUNCHER=%REPO_DIR%start_mcp.bat"
set "SHORTCUT=%STARTUP_DIR%\wsl-mcp-shutdown.bat"

echo.
echo  ============================================
echo   wsl-mcp-shutdown  ^|  Installer
echo  ============================================
echo.

:: ── 1. Check Python ────────────────────────────────────────
echo [1/5] Checking Python...
python --version >nul 2>&1
if errorlevel 1 (
    echo  ERROR: Python not found on PATH.
    echo  Install Python 3.9+ from https://python.org and re-run this script.
    goto :fail
)
for /f "tokens=*" %%v in ('python --version 2^>^&1') do set PYVER=%%v
echo  Found: %PYVER%

:: ── 2. Create virtual environment ──────────────────────────
echo.
echo [2/5] Creating virtual environment in .venv ...
if exist "%VENV_DIR%" (
    echo  .venv already exists — skipping creation.
) else (
    python -m venv "%VENV_DIR%"
    if errorlevel 1 goto :fail
    echo  Created .venv
)

:: ── 3. Install dependencies ─────────────────────────────────
echo.
echo [3/5] Installing Python dependencies (mcp[cli]) ...
"%VENV_DIR%\Scripts\pip.exe" install --quiet --upgrade pip
"%VENV_DIR%\Scripts\pip.exe" install --quiet "mcp[cli]"
if errorlevel 1 (
    echo  ERROR: pip install failed.
    goto :fail
)
echo  Dependencies installed.

:: ── 4. Write the launcher batch file ───────────────────────
echo.
echo [4/5] Writing launcher: start_mcp.bat ...
(
    echo @echo off
    echo :: wsl-mcp-shutdown launcher — auto-generated by install.bat
    echo :: Edit MCP_SHUTDOWN_TOKEN and MCP_SHUTDOWN_PORT here if desired.
    echo.
    echo set "MCP_SHUTDOWN_TOKEN="
    echo set "MCP_SHUTDOWN_PORT=8000"
    echo.
    echo cd /d "%REPO_DIR%"
    echo "%VENV_DIR%\Scripts\python.exe" shutdown_server.py
) > "%LAUNCHER%"
echo  Written: %LAUNCHER%

:: ── 5. Add to Windows Startup folder ───────────────────────
echo.
echo [5/5] Adding to Windows Startup folder...
copy /Y "%LAUNCHER%" "%SHORTCUT%" >nul
if errorlevel 1 (
    echo  WARNING: Could not copy to Startup folder.
    echo  You can start the server manually by running: start_mcp.bat
) else (
    echo  Startup shortcut created: %SHORTCUT%
)

:: ── Done ────────────────────────────────────────────────────
echo.
echo  ============================================
echo   Installation complete!
echo  ============================================
echo.
echo  Next steps:
echo   1. (Optional) Open start_mcp.bat and set MCP_SHUTDOWN_TOKEN
echo      to a secret value, then save.
echo   2. Run start_mcp.bat now, or reboot — it will auto-start on login.
echo   3. From WSL, configure your MCP client (type: streamable-http) to connect to:
echo         http://localhost:8000
echo.
echo  To uninstall, run: uninstall.bat
echo.
goto :eof

:fail
echo.
echo  Installation FAILED. See error above.
exit /b 1
